name: Run Selenium Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies and build app
        run: |
          npm install
          npm run build --if-present

      - name: Start Node.js app in background
        run: |
          npm start &
          sleep 5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver_manager

      - name: Run Selenium test
        run: python test/CasoPrueba1.py
