name: Run Selenium Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Start Node.js app in the background
        run: |
          npm start &
          # Esperar hasta que el servidor esté listo
          until curl --silent --fail http://localhost:3000/; do
            echo "Esperando a que el servidor esté disponible..."
            sleep 5
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver_manager

      - name: Run Selenium tests
        run: python test/CasoPrueba1.py